### ISSUE TITLE
Make Trace functional

### ISSUE THREAD

**Issue by du-lab** [du-lab/Trace#1]
TODO:

- Make the original source code of Trace executable: fix the reshape error in step 2 and execute step 3 (prediction module).

**Comment by du-lab** [comment]
Progress:
- Jerry has already made Trace functional on his own personal laptop.

TODO:
- Jerry: commit the code to Github
- Rasmus: Clone the repository to your iMac and test it.
- Alex: provide LC-MS data to Jerry (done)
- Jerry: train a Trace model using LC-MS data and test the performance of Trace on this LC-MS data.

**Comment by jerrychen04** [comment]
- Trace is now functional and processes each image successfully, filling in the empty area with the correct shapes of zeroes.
- LC-MS data runs through all modules using pre-trained models
- Provided data runs through all modules using pre-trained models
